kind: pipeline
type: docker
name: default

steps:
  - name: install & build
    image: node:18
    commands:
      - npm install

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host: 10.24.13.167
      username: Dockeradmin
      port: 22
      source: "./"
      target: "/home/Dockeradmin/deploy"
      key:
        from_secret: ssh_key # secret staat op drone op de browser